### ISSUE TITLE
Need to provide attribution someplace for Open EdX

### ISSUE THREAD

**Issue by kentfuka** [QueriumCorp/edx-platform#18]
Kent: We need to provide attribution for Open EdX someplace on the site.

**Comment by lpm0073** [comment]
glad this came up. edX provides precise guidelines on how they want attribution to appear on the site, which basically is a "powered by open edx" logo in the bottom-right of the footer, plus, recognition of their legal trademark of the edX and Open edX names." i have canned html to take care of all of this.
