### ISSUE TITLE
Kent: Password reset email is a plain EdX template with EdX logo not Rover

### ISSUE THREAD

**Issue by kentfuka** [QueriumCorp/edx-platform#22]
This is bound to confuse students and instructors.  Doesn't need to get fixed ASAP, but should be on the punchlist to fix.

**Comment by lpm0073** [comment]
users aren't supposed to ever need passwords, so that leaves me wondering what we should if/when some user finds themselves in this work flow?

* the email body is an html template that follows the same syntx, semantics and object models of the UI templates.

**Comment by kentfuka** [comment]
Great question.  If we are sending all instructors and students to OpenStax
to login then they should not get to the 'forgot my password' link on a
direct-to-Rover login page.  However, the current instructor login page
seems to offer both direct login and login via the OpenStax button, so
people might still click this link.  In this case the email we send them
might say something like:

'if you originally registered on the OpenStax.org website, you can go HERE<
https://accounts.openstax.org/login> and click the 'Trouble logging in?'
link for assistance.

The above URL would be the one they would get to from the openstax.org home
page.  There might be a different one on whatever login page they reach
from the oAuth-based button for login on the Rover login page.

Kent
---
Kent Fuka
*President & CEO*

<http://www.linkedin.com/company/querium-corporation?trk=hb_tab_compy_id_2942182>

*Fast Company's Top 10 Most Innovative Education Companies for 2016*

Work: (512) 833-6955 ext. 501
Mobile: (512) 656-1313
E-mail: kent@querium.com
LinkedIn: kentfuka <http://www.linkedin.com/in/kentfuka/>
5806 Mesa Drive, Suite 250
Austin, Texas 78731

**Comment by lpm0073** [comment]
I think we can close this without further action. barring a wildly broken oauth process, the open edx login and registration screens should now be permanently hidden from users.
