### ISSUE TITLE
Add the Open edX Gradebook

### ISSUE THREAD

**Issue by lpm0073** [QueriumCorp/edx-platform#26]
What do we need to do to add the gradebook shown in 16.3.4 of

https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/open-release-ginkgo.master/student_progress/course_grades.html

**Comment by kentfuka** [comment]
FYI, David Harris had requested a new button next to the 'Student View'
button in AM which takes an instructor straight to this gradebook.

Kent
---
Kent Fuka
*President & CEO*

<http://www.linkedin.com/company/querium-corporation?trk=hb_tab_compy_id_2942182>

*Fast Company's Top 10 Most Innovative Education Companies for 2016*

Work: (512) 833-6955 ext. 501
Mobile: (512) 656-1313
E-mail: kent@querium.com
LinkedIn: kentfuka <http://www.linkedin.com/in/kentfuka/>
5806 Mesa Drive, Suite 250
Austin, Texas 78731

**Comment by kentfuka** [comment]
This is now done.
