### ISSUE TITLE
Kent: Can't change assignment due dates if course start date is in the future

### ISSUE THREAD

**Issue by kentfuka** [QueriumCorp/edx-platform#28]
When you create a course, if you set the 'Start Date' to be a date in the future (which is perfectly reasonable), you cannot then edit the due dates of assignments in that course.  For an instructor, this seems nonsensical.  Changing the course start date back to some date in the past doesn't fix the problem, so it seems related to how the assignment due dates are first set up when you set the overall course dates in the course Settings.

David Harris from OpenStax created himself a course where he could not then edit the due dates of individual assignments.  The assignments show the 'clockface' icon instead of the 'Calendar' icon, so you cannot click on the due date to change it.

I was able to reproduce the problem, and I have a clue about the cause, but no idea why the code works as it does.

Here's a link to his course that is in this state:

https://am.roveropenstax.com/course/course-v1:CCCD+OS9471721_7e10+Spring2019_Shefton_MWF8-8:50

Note that every assignment in the above course shows the clock icon instead of the calendar icon next to the due date, and those due dates are not editable.  I'll be curious to see if they become editable after 6:00 UTC on 2/28/2019 (tomorrow).

I can reproduce this. I set up the course with these dates:

Start 2/28/2019 6:00 UTC
End 5/19/2919 23:59
Enrollment Start 2/25/2019 6:00
Enrollment End 4/1/2019 00:00

Those look like reasonable dates.  My first clue is that if you set the course dates to something broader like '1/1/2019-12/31/2019' you don't see this problem of non-editable assignment due dates.  I think that clue is that the course start date is a date in the past rather than a date in the future, but this is just a guess.

To confirm this, I created an identical course, but I set the Start date back 2 days to 2/26/2019 at 6:00UTC (one day in the past), and the problem does not occur.  I started looking at the code, and indeed it looks like this is the specified behavior given what I see in the code.

FYI, the template code has this:

/edx/app/edxapp/edx-platform/cms/templates/js/course-outline.underscore

```
                           <% if (!course.get('self_paced')) { %>
                                <% if (xblockInfo.get('released_to_students')) { %>
                                    <!-- McDaniel Nov-2018: begin copied snippet -->
                                    <% if (xblockInfo.isEditableOnCourseOutline()) { %>
                                        <span class="action-item action-configure">
                                            <a href="#" data-tooltip="Set assignment due date" class="rover-link configure-button action-button">
                                                <span class="icon fa fa-calendar" aria-hidden="true"></span>
                                                <span class="sr action-button-text">Set assignment due date</span>
                                                <%- gettext('Released:') %>
                                                <% if (xblockInfo.get('release_date')) { %>
                                                    <%- xblockInfo.get('release_date') %>
                                                <% } %>
                                            </a>
                                            <!-- McDaniel Nov-2018: end copied snippet -->
                                        </span>
                                    <% } %>
                                <% } else if (xblockInfo.get('release_date')) { %>
                                    <span class="icon fa fa-clock-o" aria-hidden="true"></span>
                                    <%- gettext('Scheduled:') %>
                                    <% if (xblockInfo.get('release_date')) { %>
                                        <%- xblockInfo.get('release_date') %>
                                    <% } %>

```
Assuming this is the template for the right page, then from the code it looks like I should care about what xblockInfo.get('released_to_students') is.  I also supposed that it could somehow have been set to be a self-paced course, or but that seemed unlikely.

/edx/app/edxapp/edx-platform/cms/static/js/models/xblock_info.js has this:

```
            /**
             * True if the release date of the xblock is in the past.
             */

            released_to_students: null,
```

and isEditableOnCourseOutline() test doesn't seem like the cause:

```
      /**
        * Check if we can edit current XBlock or not on Course Outline page.
        * @return {Boolean}
        */

        isEditableOnCourseOutline: function() {
            return this.isSequential() || this.isChapter() || this.isVertical();
        }

```

Since these assignments are 'sequentials', I think the 'isEditableOnCourseOutline' test should pass. If I believe the comment about 'released_to_students' meaning that the release date is in the past, then it seems like the code won't let you edit something until after the release date.  My problem is that I'm not sure that release date the commend refers to, since it says the release date of the Xblock.

**Comment by kentfuka** [comment]
In Jira as
[ROV-16](https://querium.atlassian.net/projects/ROV/issues/ROV-16)

**Comment by lpm0073** [comment]
i updated course_outline.underscore to add the edit anchors to the two other possibilities in the template: a clock icon for "Scheduled" and a clock icon for "Un-scheduled".
